print(bool("abc"))
print(bool(531))
print(bool(["hello","jennie","i am",22]))
print("none :",bool(None))
print("False :",bool(False))
print("0 :",bool(0))
print("Empty String :",bool(""))
print("Nothing : ",bool())
print("isinstance :",isinstance(200,int))